name: Tests
on: push
jobs:
  tests:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          graphviz_bin: /usr/bin/
        - os: windows-latest
          graphviz_bin: ""
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
        architecture: x64
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - run: pip install nox
    - run: pip install poetry
    - name: Lint
      run: nox -s lint
    - name: Run test suite
      run: nox -s tests
      env:
        GRAPHVIZ_BIN: ${{ matrix.graphviz_bin }}
 
