name: Tests
on: push
jobs:
  tests:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
        architecture: x64
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - run: which dot
    - run: pip install nox
    - run: pip install poetry
    - run: nox
 
